# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. 2 is the newest version and shouldnt' be changed.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = "ubuntu/trusty64"

	# Create a private network, which allows host-only access to the machine using a specific IP.
	config.vm.network "private_network", ip: "75.75.75.10"

	# Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
	# The second argument is the path on the guest to mount the folder.
	config.vm.synced_folder "./", "/var/www/html"

	# Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
	config.vm.provision :shell, path: "bootstrap.sh"

	# Override the default VM Settings
	config.vm.provider "virtualbox" do |v|
		v.name = "Ubuntu - Apache2"
		v.memory = 4096
		v.cpus = 2
	end


	# config.vm.network :forwarded_port, guest: 2368, host: 1234, auto_correct: true
	# config.vm.network "forwarded_port", guest: 80, host: 8080


	# --------------
	#    Notes
	# --------------
	# Server vhosts site directory configuration = /etc/apache2/sites-available/000-default.conf
	# Mac local hosts file location = /private/etc/hosts

end